# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1feb0410-68dd-48ed-b93e-b2f5fc610a7e'
  imageRepository: 'sengteamvegaweb'
  containerRegistry: 'vegawebteam4.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker-compose.yml'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build container
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'eddad6ab-c78b-4843-ab26-400912a94327'
        azureContainerRegistry: $(dockerRegistryServiceConnection)
        dockerComposeFile: 'docker-compose.yml'
        action: Build services
    - task: DockerCompose@0
      inputs:
       containerregistrytype: Azure Container Registry
       azureSubscription: 'eddad6ab-c78b-4843-ab26-400912a94327'
       azureContainerRegistry: $(dockerRegistryServiceConnection)
       dockerComposeFile: 'docker-compose.yml'
       action: Push services
       includeSourceTags: true
       includeLatestTag: true
